version: "3.9"
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    command: make runserver
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

volumes:
  postgres_data: null