name: main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install docker and docker-compose
        uses: docker/setup-buildx-action@v2
        with:
          docker-version: '20.10.7'

      - name: Create .env file for tests
        run: echo "ENV_STAGE=${{ secrets.ENV_STAGE }}" > .env

      - name: Build, test, lint and clean up project
        run: make tests
